### ISSUE TITLE
Picklable file iterator?

### ISSUE THREAD

**Issue by bartvm** [dwf/picklable_itertools#24]
@dwf Wondering if you consider this within the scope of the framework.

File handles are iterators, and they can't be pickled.

```python
>>> f = open('README.md')
>>> f
<open file 'README.md', mode 'r' at 0x7f13b1360d20>
>>> it = iter(f)
>>> it
<open file 'README.md', mode 'r' at 0x7f13b1360d20>
>>> next(it)
'picklable_itertools\n'
>>> cPickle.dumps(it)
TypeError: can't pickle file objects
```

Analogously to `ordered_sequence_iterator`, can I add a `file_iterator`? It will be a bit more involved, because it needs to handle a variety of things through custom `__getstate__` and `__setstate__` methods:

* Upon pickling, close and remove file handle
* When unpickling, re-open the file, re-iterate over the lines until we get back to where we were
* Have sensible defaults for if the file is not available in the unpickled environment, is no longer writable, etc. Dill implements all of this, so we can steal a lot of the behaviour from there.

**Comment by dwf** [comment]
Sounds good to me.
