### ISSUE TITLE
itertoolz?

### ISSUE THREAD

**Issue by bartvm** [dwf/picklable_itertools#28]
Would be great to extend this package to contain `itertoolz` implementations as well. The one that I can think of that are particularly handy are [`partition` and `partition_all`](http://toolz.readthedocs.org/en/latest/api.html#toolz.itertoolz.partition_all), so that returning batches becomes: `partition(batch_size, xrange(num_examples))`.

**Comment by dwf** [comment]
Seems like a fine idea to me. Maybe `picklable_itertools.extras` to distinguish it from the stuff that mirrors the stdlib?

**Comment by dwf** [comment]
Seems like, in the case of partition etc., what we really want is a version that operates on Numpy arrays directly.
